### PR TITLE
syncing repo with FGMEMBERS

### PR DESCRIPTION
**Pull request by FGDATA**
merging this will now have your new changes
I recomend
1. merge
2. git pull your local clone

and that's it. you should be good

### CODE REVIEW

**Comment by it0uchpods** [comment]
This I cannot du. I NEED to merge this into FGMEMBERS. If I merge this, it breaks my model. I made a mistake and it synced into the wrong way, and I need to reverse this. I need to merge it0uchpods/MD-88 into FGMEBERS-NONGPL/MD-88, not the other way around.

**Comment by FGDATA** [comment]
https://github.com/it0uchpods/MD-88/pull/1/files
Check well. No changes will occur after merging back. FGMEMBERS already has your fixes.
The link above list only changes your repo will have if merged.

**Comment by it0uchpods** [comment]
I hope yuo are right, I will merge. Thanks.

**Comment by FGDATA** [comment]
yup. Now both repos are synced, and all your updates are in both. 
Remember to "git pull" in your computer before continuing making changes
IH-COL

**Pull request merged**
